# Generated by Django 6.0.3 on 2026-03-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_registercarowner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registercarowner',
            new_name='carowner',
        ),
    ]
