# Generated by Django 4.2 on 2026-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_contact_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
